#la siguiente es una regla, donde el target es un objeto o archivo llamado hello
#seguido de [:] se indican archivos u objetos que se conocen como dependecias
#estas dependecias deben de existir para que los comandos se ejecuten
#los comandos son indicados mediante indentacion con TAB

hello:
	echo "Hola mundo!"
